# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    tags: 
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14.x']

    steps:
    - uses: actions/checkout@v2
    - name: Set tag in env...
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env:
        API_KEY: ${{ secrets.API_KEY }}
        SPREADSHEET_KEY: ${{ secrets.SPREADSHEET_KEY }}
    - run: npm install
    # Need to update version automatically
    # - run: npm version ${{ env.RELEASE_VERSION }}
    - run: npm run build
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: |
          ./
          !./node_modules

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: build
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_AUTH_TOKEN }}

